name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Hi and welcome here. Thanks for the issue, we will have a look asap'' first issue'
        pr-message: 'Welcome and thanks for the contribution!'' first pr'
